apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: konflux-unified-build
  labels:
    app.kubernetes.io/part-of: konflux-konflux-test
spec:
  description: |
    Builds two container images in a single pipeline run.
    Image 2 receives Image 1's digest as build arg.
    Returns Image 1 as the primary result.

  params:
  - name: git-url
    type: string
    description: Source repository URL
  - name: revision
    type: string
    description: Git revision to build
    default: master
  - name: output-image-1
    type: string
    description: Fully qualified output image for Image 1
  - name: output-image-2
    type: string
    description: Fully qualified output image for Image 2
  - name: dockerfile-1
    type: string
    description: Path to Containerfile for Image 1
    default: image1/Containerfile
  - name: dockerfile-2
    type: string
    description: Path to Containerfile for Image 2
    default: image2/Containerfile
  - name: path-context
    type: string
    description: Build context directory
    default: .

  workspaces:
  - name: workspace
  - name: git-auth
    optional: true

  results:
  - name: IMAGE_URL
    description: Image 1 URL (primary result for Konflux)
    value: $(tasks.build-image-1.results.IMAGE_URL)
  - name: IMAGE_DIGEST
    description: Image 1 digest (primary result for Konflux)
    value: $(tasks.build-image-1.results.IMAGE_DIGEST)
  - name: IMAGE_2_URL
    description: Image 2 URL (for reference)
    value: $(tasks.build-image-2.results.IMAGE_URL)
  - name: IMAGE_2_DIGEST
    description: Image 2 digest (for reference)
    value: $(tasks.build-image-2.results.IMAGE_DIGEST)
  - name: CHAINS-GIT_URL
    description: Git repository URL for provenance
    value: $(tasks.git-clone.results.url)
  - name: CHAINS-GIT_COMMIT
    description: Git commit SHA for provenance
    value: $(tasks.git-clone.results.commit)

  tasks:

  # Task 1: Clone the repository
  - name: git-clone
    taskRef:
      resolver: bundles
      params:
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1
      - name: name
        value: git-clone
      - name: kind
        value: Task
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    workspaces:
    - name: output
      workspace: workspace
    - name: basic-auth
      workspace: git-auth

  # Task 2: Build Image 1 (primary image)
  - name: build-image-1
    runAfter:
    - git-clone
    taskRef:
      resolver: bundles
      params:
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.1
      - name: name
        value: buildah
      - name: kind
        value: Task
    params:
    - name: IMAGE
      value: $(params.output-image-1)
    - name: DOCKERFILE
      value: $(params.dockerfile-1)
    - name: CONTEXT
      value: $(params.path-context)
    workspaces:
    - name: source
      workspace: workspace

  # Task 3: Build Image 2 (metadata image with Image 1's digest)
  - name: build-image-2
    runAfter:
    - build-image-1
    taskRef:
      resolver: bundles
      params:
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.1
      - name: name
        value: buildah
      - name: kind
        value: Task
    params:
    - name: IMAGE
      value: $(params.output-image-2)
    - name: DOCKERFILE
      value: $(params.dockerfile-2)
    - name: CONTEXT
      value: $(params.path-context)
    - name: BUILD_ARGS
      value:
      - IMAGE1_DIGEST=$(tasks.build-image-1.results.IMAGE_DIGEST)
      - IMAGE1_URL=$(tasks.build-image-1.results.IMAGE_URL)
    workspaces:
    - name: source
      workspace: workspace
