apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/psav/konflux-test?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
    pipelinesascode.tekton.dev/max-keep-runs: '3'
  labels:
    appstudio.openshift.io/application: konflux-test
    appstudio.openshift.io/component: app
    pipelines.appstudio.openshift.io/type: build
  name: app-on-push
  namespace: rosa-log-router-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image-1
    value: quay.io/redhat-user-workloads/rosa-log-router-tenant/app:{{revision}}
  - name: output-image-2
    value: quay.io/redhat-user-workloads/rosa-log-router-tenant/metadata-scanner:{{revision}}
  - name: dockerfile-1
    value: image1/Containerfile
  - name: dockerfile-2
    value: image2/Containerfile
  - name: path-context
    value: .

  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/psav/konflux-test
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline/unified-build.yaml

  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
