apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/psav/konflux-test?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "master"
    pipelinesascode.tekton.dev/max-keep-runs: '3'
  labels:
    appstudio.openshift.io/application: konflux-test
    appstudio.openshift.io/component: app
    pipelines.appstudio.openshift.io/type: build
  name: app-on-pull-request
  namespace: rosa-log-router-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rosa-log-router-tenant/app:on-pr-{{revision}}
  - name: dockerfile
    value: image1/Containerfile
  - name: path-context
    value: .

  pipelineRef:
    resolver: bundles
    params:
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta:latest
    - name: name
      value: docker-build-oci-ta
    - name: kind
      value: Pipeline

  taskRunTemplate:
    serviceAccountName: build-pipeline-app

  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
