apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/psav/konflux-test?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "master"
    pipelinesascode.tekton.dev/max-keep-runs: '3'
  labels:
    appstudio.openshift.io/application: konflux-test
    appstudio.openshift.io/component: metadata-scanner
    pipelines.appstudio.openshift.io/type: build
  name: metadata-scanner-on-push
  namespace: rosa-log-router-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: SRC_REPO_URL
    value: '{{source_url}}'
  - name: SRC_REF
    value: '{{revision}}'
  - name: SRC_PATH
    value: pko-package
  - name: DST_URL
    value: quay.io/redhat-user-workloads/rosa-log-router-tenant/metadata-scanner:{{revision}}

  pipelineRef:
    resolver: bundles
    params:
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/pipeline-package-operator-package:latest
    - name: name
      value: package-operator-package
    - name: kind
      value: Pipeline

  taskRunTemplate:
    serviceAccountName: build-pipeline-metadata-scanner

  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
