apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/psav/konflux-test?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "master"
    pipelinesascode.tekton.dev/max-keep-runs: '3'
  labels:
    appstudio.openshift.io/application: konflux-test
    appstudio.openshift.io/component: metadata-scanner
    pipelines.appstudio.openshift.io/type: build
  name: metadata-scanner-on-push
  namespace: rosa-log-router-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: source-image
    value: quay.io/redhat-user-workloads/rosa-log-router-tenant/app:{{revision}}

  pipelineSpec:
    params:
    - name: git-url
    - name: revision
    - name: source-image
      description: Image 1 URL to extract metadata from

    results:
    - name: IMAGE_URL
      description: Extracted Image 2 URL for scanning
      value: $(tasks.extract-metadata.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      description: Extracted Image 2 digest for scanning
      value: $(tasks.extract-metadata.results.IMAGE_DIGEST)
    - name: CHAINS-GIT_URL
      description: Git repository URL for provenance
      value: $(tasks.git-clone.results.url)
    - name: CHAINS-GIT_COMMIT
      description: Git commit SHA for provenance
      value: $(tasks.git-clone.results.commit)

    workspaces:
    - name: workspace
      description: Workspace for git clone (needed for CHAINS results)

    tasks:
    - name: git-clone
      taskRef:
        resolver: bundles
        params:
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1
        - name: name
          value: git-clone
        - name: kind
          value: Task
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.revision)
      workspaces:
      - name: output
        workspace: workspace
      - name: basic-auth
        workspace: git-auth

    - name: extract-metadata
      runAfter:
      - git-clone
      taskSpec:
        params:
        - name: source-image
        results:
        - name: IMAGE_URL
          description: Extracted Image 2 URL
        - name: IMAGE_DIGEST
          description: Extracted Image 2 digest
        steps:
        - name: extract
          image: quay.io/skopeo/stable:latest
          script: |
            #!/bin/sh
            set -e

            echo "Inspecting source image: $(params.source-image)"

            # Construct Image 2 URL by adding metadata- prefix to the tag
            # e.g., app:abc123 -> app:metadata-abc123
            IMAGE2_URL=$(echo "$(params.source-image)" | sed 's/:/:metadata-/')

            echo "Constructed Image 2 URL: $IMAGE2_URL"

            # Now inspect Image 2 to get its actual digest (only the first/main one)
            IMAGE2_DIGEST=$(skopeo inspect docker://${IMAGE2_URL} | \
              grep '"Digest"' | \
              head -n 1 | \
              sed 's/.*"Digest":[[:space:]]*"\([^"]*\)".*/\1/')

            if [ -z "$IMAGE2_DIGEST" ]; then
              echo "ERROR: Could not extract digest from Image 2"
              exit 1
            fi

            echo "Resolved Image 2 digest: $IMAGE2_DIGEST"

            echo "Image 2 URL: ${IMAGE2_URL}"
            echo "Image 2 Digest: ${IMAGE2_DIGEST}"

            # Set results for Konflux to scan
            echo -n "${IMAGE2_URL}" > $(results.IMAGE_URL.path)
            echo -n "${IMAGE2_DIGEST}" > $(results.IMAGE_DIGEST.path)

            echo "Metadata extraction complete. Konflux will now scan Image 2."
      params:
      - name: source-image
        value: $(params.source-image)

  taskRunTemplate:
    serviceAccountName: build-pipeline-metadata-scanner

  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
