apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/psav/konflux-test?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "master"
    pipelinesascode.tekton.dev/max-keep-runs: '3'
  labels:
    appstudio.openshift.io/application: konflux-test
    appstudio.openshift.io/component: metadata-scanner
    pipelines.appstudio.openshift.io/type: build
  name: metadata-scanner-on-push
  namespace: rosa-log-router-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: source-image
    value: quay.io/redhat-user-workloads/rosa-log-router-tenant/app:{{revision}}

  pipelineSpec:
    params:
    - name: git-url
    - name: revision
    - name: source-image
      description: Image 1 URL to extract metadata from

    results:
    - name: IMAGE_URL
      description: Extracted Image 2 URL for scanning
      value: $(tasks.extract-metadata.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      description: Extracted Image 2 digest for scanning
      value: $(tasks.extract-metadata.results.IMAGE_DIGEST)

    tasks:
    - name: extract-metadata
      taskSpec:
        params:
        - name: source-image
        results:
        - name: IMAGE_URL
          description: Extracted Image 2 URL
        - name: IMAGE_DIGEST
          description: Extracted Image 2 digest
        steps:
        - name: extract
          image: quay.io/skopeo/stable:latest
          script: |
            #!/bin/sh
            set -e

            echo "Inspecting source image: $(params.source-image)"

            # Inspect the image and extract labels
            INSPECT_OUTPUT=$(skopeo inspect docker://$(params.source-image))

            # Extract the Image 2 URL from labels
            IMAGE2_URL=$(echo "$INSPECT_OUTPUT" | jq -r '.Labels["io.konflux.poc.metadata-image.url"] // empty')

            if [ -z "$IMAGE2_URL" ]; then
              echo "ERROR: Could not find io.konflux.poc.metadata-image.url label"
              exit 1
            fi

            echo "Found Image 2 URL in labels: $IMAGE2_URL"

            # Now inspect Image 2 to get its actual digest
            IMAGE2_INSPECT=$(skopeo inspect docker://${IMAGE2_URL})
            IMAGE2_DIGEST=$(echo "$IMAGE2_INSPECT" | jq -r '.Digest')

            echo "Resolved Image 2 digest: $IMAGE2_DIGEST"

            echo "Image 2 URL: ${IMAGE2_URL}"
            echo "Image 2 Digest: ${IMAGE2_DIGEST}"

            # Set results for Konflux to scan
            echo -n "${IMAGE2_URL}" > $(results.IMAGE_URL.path)
            echo -n "${IMAGE2_DIGEST}" > $(results.IMAGE_DIGEST.path)

            echo "Metadata extraction complete. Konflux will now scan Image 2."
      params:
      - name: source-image
        value: $(params.source-image)

  taskRunTemplate:
    serviceAccountName: build-pipeline-metadata-scanner

  workspaces: []
